### ISSUE TITLE
Make ToC links go to the title rather than the content

### ISSUE THREAD

**Issue by eteq** [aasorg/hacks-collector#17]
Right now the ToC links added in #16 go to the *content* rather than the title of a hack, despite the ``id`` being defined in the header (see https://aasorg.github.io/hacks-collector/aas229.html#titleanchor1). 

@zemogle, as the originator of this page layout (for the dotastronomy hacks collector): do you know why this is happening or know what we might be able to do to fix this?

**Comment by pllim** [comment]
I figured it out. It is because the title is actually obscured by the top banner thingy. The proper fix is to adjust CSS to somehow not have top banner obscure real contents, but rather act like separate frames. But I have a work around in #18.
